-- Run as ACCOUNTADMIN. Adjust names for your organization.

CREATE WAREHOUSE IF NOT EXISTS GRC_WH
  WAREHOUSE_SIZE = 'XSMALL'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE;

CREATE ROLE IF NOT EXISTS GRC_ADMIN;
CREATE ROLE IF NOT EXISTS GRC_DEVELOPER;
CREATE ROLE IF NOT EXISTS GRC_ANALYST;
CREATE ROLE IF NOT EXISTS GRC_STREAMLIT_APP;

GRANT USAGE ON WAREHOUSE GRC_WH TO ROLE GRC_DEVELOPER;
GRANT USAGE ON WAREHOUSE GRC_WH TO ROLE GRC_ANALYST;
GRANT USAGE ON WAREHOUSE GRC_WH TO ROLE GRC_STREAMLIT_APP;
GRANT USAGE ON WAREHOUSE GRC_WH TO ROLE GRC_ADMIN;

-- After database exists (run DDL first), grant schema privileges:
-- GRANT USAGE ON DATABASE GRC_DEMO_DB TO ROLE GRC_ANALYST;
-- GRANT USAGE ON ALL SCHEMAS IN DATABASE GRC_DEMO_DB TO ROLE GRC_ANALYST;
-- GRANT SELECT ON ALL VIEWS IN SCHEMA GRC_DEMO_DB.ANALYTICS TO ROLE GRC_ANALYST;
