USE DATABASE GRC_DEMO_DB;
USE SCHEMA RAW;

CREATE FILE FORMAT IF NOT EXISTS FF_JSON_ARRAY
  TYPE = JSON
  STRIP_OUTER_ARRAY = TRUE;

CREATE FILE FORMAT IF NOT EXISTS FF_JSON_ND
  TYPE = JSON
  STRIP_OUTER_ARRAY = FALSE;

CREATE STAGE IF NOT EXISTS INTERNAL_GRC_STAGE
  FILE_FORMAT = FF_JSON_ARRAY
  COMMENT = 'PUT legacy server/data JSON here, e.g. @INTERNAL_GRC_STAGE/legacy_json/';
