-- Grants for Streamlit app owner role (run as securityadmin or equivalent).
-- Replace GRC_STREAMLIT_APP with the role that OWNS the Streamlit app object.


-- App runtime needs warehouse
GRANT USAGE ON WAREHOUSE GRC_WH TO ROLE GRC_STREAMLIT_APP;

USE DATABASE GRC_DEMO_DB;

GRANT USAGE ON SCHEMA RAW TO ROLE GRC_STREAMLIT_APP;
GRANT USAGE ON SCHEMA CURATED TO ROLE GRC_STREAMLIT_APP;
GRANT USAGE ON SCHEMA ANALYTICS TO ROLE GRC_STREAMLIT_APP;
GRANT USAGE ON SCHEMA ML TO ROLE GRC_STREAMLIT_APP;
GRANT USAGE ON SCHEMA APP TO ROLE GRC_STREAMLIT_APP;

GRANT SELECT ON ALL VIEWS IN SCHEMA ANALYTICS TO ROLE GRC_STREAMLIT_APP;
GRANT SELECT ON ALL TABLES IN SCHEMA CURATED TO ROLE GRC_STREAMLIT_APP;
GRANT SELECT ON ALL TABLES IN SCHEMA ML TO ROLE GRC_STREAMLIT_APP;
GRANT SELECT ON ALL TABLES IN SCHEMA APP TO ROLE GRC_STREAMLIT_APP;

-- Cortex log insert
GRANT INSERT ON TABLE ML.ML_CORTEX_RUN_LOG TO ROLE GRC_STREAMLIT_APP;

-- Future: explicit future grants
-- GRANT SELECT ON FUTURE TABLES IN SCHEMA CURATED TO ROLE GRC_STREAMLIT_APP;
