USE DATABASE GRC_DEMO_DB;
SELECT 'RAW.COMPANIES_RAW' AS tbl, COUNT(*) AS c FROM RAW.COMPANIES_RAW
UNION ALL SELECT 'CURATED.DIM_OPCO', COUNT(*) FROM CURATED.DIM_OPCO
UNION ALL SELECT 'CURATED.FACT_REGULATORY_CHANGE', COUNT(*) FROM CURATED.FACT_REGULATORY_CHANGE
UNION ALL SELECT 'ML.ML_PREDICTION_RISK_SCORE', COUNT(*) FROM ML.ML_PREDICTION_RISK_SCORE;
