USE DATABASE GRC_DEMO_DB;
USE SCHEMA RAW;

CREATE OR REPLACE TABLE COMPANIES_RAW (
  ingest_id VARCHAR(36) DEFAULT UUID_STRING(),
  ingest_ts TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
  source_file VARCHAR(500),
  payload VARIANT
);

CREATE OR REPLACE TABLE ONBOARDING_OPCOS_RAW (
  ingest_id VARCHAR(36) DEFAULT UUID_STRING(),
  ingest_ts TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
  source_file VARCHAR(500),
  payload VARIANT
);

CREATE OR REPLACE TABLE OPCO_MULTI_SHAREHOLDERS_RAW (
  ingest_id VARCHAR(36) DEFAULT UUID_STRING(),
  ingest_ts TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
  source_file VARCHAR(500),
  payload VARIANT
);

CREATE OR REPLACE TABLE CHANGES_RAW (
  ingest_id VARCHAR(36) DEFAULT UUID_STRING(),
  ingest_ts TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
  source_file VARCHAR(500),
  payload VARIANT
);

CREATE OR REPLACE TABLE FEED_META_RAW (
  ingest_id VARCHAR(36) DEFAULT UUID_STRING(),
  ingest_ts TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
  source_file VARCHAR(500),
  payload VARIANT
);

CREATE OR REPLACE TABLE TASKS_RAW (
  ingest_id VARCHAR(36) DEFAULT UUID_STRING(),
  ingest_ts TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
  source_file VARCHAR(500),
  payload VARIANT
);

CREATE OR REPLACE TABLE AUDIT_RAW (
  ingest_id VARCHAR(36) DEFAULT UUID_STRING(),
  ingest_ts TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
  source_file VARCHAR(500),
  payload VARIANT
);

CREATE OR REPLACE TABLE POA_RAW (
  ingest_id VARCHAR(36) DEFAULT UUID_STRING(),
  ingest_ts TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
  source_file VARCHAR(500),
  payload VARIANT
);

CREATE OR REPLACE TABLE LICENCES_RAW (
  ingest_id VARCHAR(36) DEFAULT UUID_STRING(),
  ingest_ts TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
  source_file VARCHAR(500),
  payload VARIANT
);

CREATE OR REPLACE TABLE CONTRACTS_RAW (
  ingest_id VARCHAR(36) DEFAULT UUID_STRING(),
  ingest_ts TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
  source_file VARCHAR(500),
  payload VARIANT
);

CREATE OR REPLACE TABLE IP_RAW (
  ingest_id VARCHAR(36) DEFAULT UUID_STRING(),
  ingest_ts TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
  source_file VARCHAR(500),
  payload VARIANT
);

CREATE OR REPLACE TABLE LITIGATIONS_RAW (
  ingest_id VARCHAR(36) DEFAULT UUID_STRING(),
  ingest_ts TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
  source_file VARCHAR(500),
  payload VARIANT
);

CREATE OR REPLACE TABLE DATA_SOVEREIGNTY_RAW (
  ingest_id VARCHAR(36) DEFAULT UUID_STRING(),
  ingest_ts TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
  source_file VARCHAR(500),
  payload VARIANT
);

CREATE OR REPLACE TABLE ESG_METRICS_RAW (
  ingest_id VARCHAR(36) DEFAULT UUID_STRING(),
  ingest_ts TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
  source_file VARCHAR(500),
  payload VARIANT
);

CREATE OR REPLACE TABLE FIELD_MAPPINGS_RAW (
  ingest_id VARCHAR(36) DEFAULT UUID_STRING(),
  ingest_ts TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
  source_file VARCHAR(500),
  payload VARIANT
);

CREATE OR REPLACE TABLE DEFENDER_UPLOADS_RAW (
  ingest_id VARCHAR(36) DEFAULT UUID_STRING(),
  ingest_ts TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
  source_file VARCHAR(500),
  payload VARIANT
);

CREATE OR REPLACE TABLE DEFENDER_SNAPSHOTS_RAW (
  ingest_id VARCHAR(36) DEFAULT UUID_STRING(),
  ingest_ts TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
  source_file VARCHAR(500),
  payload VARIANT
);

CREATE OR REPLACE TABLE DEFENDER_FINDINGS_RAW (
  ingest_id VARCHAR(36) DEFAULT UUID_STRING(),
  ingest_ts TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
  source_file VARCHAR(500),
  payload VARIANT
);

CREATE OR REPLACE TABLE DEFENDER_SCORES_RAW (
  ingest_id VARCHAR(36) DEFAULT UUID_STRING(),
  ingest_ts TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
  source_file VARCHAR(500),
  payload VARIANT
);

CREATE OR REPLACE TABLE DEFENDER_SUMMARIES_RAW (
  ingest_id VARCHAR(36) DEFAULT UUID_STRING(),
  ingest_ts TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
  source_file VARCHAR(500),
  payload VARIANT
);

CREATE OR REPLACE TABLE AI_MODEL_USAGE_RAW (
  ingest_id VARCHAR(36) DEFAULT UUID_STRING(),
  ingest_ts TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
  source_file VARCHAR(500),
  payload VARIANT
);
