USE DATABASE GRC_DEMO_DB;
USE SCHEMA CURATED;

CREATE OR REPLACE TABLE DIM_PARENT_HOLDING (
  parent_holding_id VARCHAR(36) DEFAULT UUID_STRING(),
  name VARCHAR(255) NOT NULL,
  source_system_id VARCHAR(128),
  created_at TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
  updated_at TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE DIM_OPCO (
  opco_id VARCHAR(36) DEFAULT UUID_STRING(),
  parent_holding_id VARCHAR(36) NOT NULL,
  name VARCHAR(255) NOT NULL,
  sector VARCHAR(128),
  business_activities VARCHAR(16777216),
  source_system_id VARCHAR(128),
  raw_profile VARIANT,
  created_at TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
  updated_at TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE DIM_FRAMEWORK (
  framework_id VARCHAR(36) DEFAULT UUID_STRING(),
  name VARCHAR(255) NOT NULL,
  jurisdiction VARCHAR(64),
  description VARCHAR(16777216),
  reference_url VARCHAR(1024),
  created_at TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE DIM_LOCATION (
  location_id VARCHAR(36) DEFAULT UUID_STRING(),
  opco_id VARCHAR(36) NOT NULL,
  location_type VARCHAR(64),
  name VARCHAR(255),
  country_code CHAR(2),
  created_at TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE DIM_LICENSING_AUTHORITY (
  authority_id VARCHAR(36) DEFAULT UUID_STRING(),
  name VARCHAR(255) NOT NULL,
  created_at TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE BRIDGE_OPCO_FRAMEWORK (
  opco_id VARCHAR(36) NOT NULL,
  framework_id VARCHAR(36) NOT NULL,
  source VARCHAR(64),
  created_at TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
  PRIMARY KEY (opco_id, framework_id)
);

CREATE OR REPLACE TABLE BRIDGE_OPCO_LICENSING_AUTHORITY (
  opco_id VARCHAR(36) NOT NULL,
  authority_id VARCHAR(36) NOT NULL,
  PRIMARY KEY (opco_id, authority_id)
);

CREATE OR REPLACE TABLE BRIDGE_OPCO_MULTI_SHAREHOLDER (
  bridge_id VARCHAR(36) DEFAULT UUID_STRING(),
  opco_id VARCHAR(36) NOT NULL,
  parent_holding_id VARCHAR(36) NOT NULL,
  percentage NUMBER(5,2) NOT NULL,
  created_at TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE DIM_LEGAL_DOCUMENT (
  document_id VARCHAR(36) DEFAULT UUID_STRING(),
  opco_id VARCHAR(36),
  parent_holding_id VARCHAR(36),
  stage_path VARCHAR(2048),
  file_name VARCHAR(512),
  mime_type VARCHAR(128),
  sha256_hex VARCHAR(64),
  uploaded_by VARCHAR(256),
  uploaded_at TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
  extracted_variant VARIANT
);

CREATE OR REPLACE TABLE DIM_DATE (
  d DATE PRIMARY KEY,
  y NUMBER(4,0),
  m NUMBER(2,0),
  d_dom NUMBER(2,0),
  quarter NUMBER(1,0),
  yq VARCHAR(8)
);
